name: $(majorMinorVersion).$(semanticVersion)
  
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  majorMinorVersion: 1.1
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]


steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: |
      src/abstractions/abstractions.csproj
      src/client/client.csproj
      src/host/host.csproj
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: |
      src/abstractions/abstractions.csproj
      src/client/client.csproj
      src/host/host.csproj
    arguments: '-c $(buildConfiguration) /p:Version=$(majorMinorVersion).$(semanticVersion)'
- task: NuGetToolInstaller@1
  displayName: 'Nuget Update'
- task: NuGetCommand@2
  displayName: 'Pack Abstractions'
  inputs:
    command: 'pack'
    packagesToPack: '**/abstractions.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  displayName: 'Pack Client'
  inputs:
    command: 'pack'
    packagesToPack: '**/client.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  displayName: 'Pack Host'
  inputs:
    command: 'pack'
    packagesToPack: '**/host.nuspec'
    versioningScheme: 'byBuildNumber'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    