name: $(majorMinorVersion).$(semanticVersion)
  
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  majorMinorVersion: 1.0
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]


steps:
