name: $(BuildDefinitionName)_1.0$(Rev:.r)
  
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/abstractions.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/client.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/host.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f9ed18cb-f0f4-4034-80ce-a9fff62b78ef'
