name: $(BuildDefinitionName)_1.0$(Rev:.r)
  
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '5.0.x'
- task: DotNetCoreCLI@2
  
  displayName: 'Build Abstractions'
  inputs:
    command: 'build'
    projects: 'src/abstractions/abstractions.csprj'
    arguments: '-c $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Build Client'
  inputs:
    command: 'build'
    projects: 'src/client/client.csprj'
    arguments: '-c $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Build Host'
  inputs:
    command: 'build'
    projects: 'src/host/host.csprj'
    arguments: '-c $(buildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/abstractions.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/client.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/host.nuspec'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f9ed18cb-f0f4-4034-80ce-a9fff62b78ef'
